//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/search", ReplyAction="http://tempuri.org/IService1/searchResponse")]
        string search(string xmlFile, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/search", ReplyAction="http://tempuri.org/IService1/searchResponse")]
        System.Threading.Tasks.Task<string> searchAsync(string xmlFile, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addPerson", ReplyAction="http://tempuri.org/IService1/addPersonResponse")]
        void addPerson(string firstName, string lastName, string newId, string newPassword, string workPhone, string cellPhone, string carrier, string cat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addPerson", ReplyAction="http://tempuri.org/IService1/addPersonResponse")]
        System.Threading.Tasks.Task addPersonAsync(string firstName, string lastName, string newId, string newPassword, string workPhone, string cellPhone, string carrier, string cat);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebApplication1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebApplication1.ServiceReference1.IService1>, WebApplication1.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string search(string xmlFile, string name) {
            return base.Channel.search(xmlFile, name);
        }
        
        public System.Threading.Tasks.Task<string> searchAsync(string xmlFile, string name) {
            return base.Channel.searchAsync(xmlFile, name);
        }
        
        public void addPerson(string firstName, string lastName, string newId, string newPassword, string workPhone, string cellPhone, string carrier, string cat) {
            base.Channel.addPerson(firstName, lastName, newId, newPassword, workPhone, cellPhone, carrier, cat);
        }
        
        public System.Threading.Tasks.Task addPersonAsync(string firstName, string lastName, string newId, string newPassword, string workPhone, string cellPhone, string carrier, string cat) {
            return base.Channel.addPersonAsync(firstName, lastName, newId, newPassword, workPhone, cellPhone, carrier, cat);
        }
    }
}
