//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace weather {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class YahooAPI_ID : global::System.Configuration.ApplicationSettingsBase {
        
        private static YahooAPI_ID defaultInstance = ((YahooAPI_ID)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new YahooAPI_ID())));
        
        public static YahooAPI_ID Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("344934ad04e3a093c42823791874ceb813057b19")]
        public string appId {
            get {
                return ((string)(this["appId"]));
            }
            set {
                this["appId"] = value;
            }
        }
    }
}
